### ISSUE TITLE
Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by chubits** [dodying/EH-Scraper#1]
Hi, is this plugin no longer supported?

I get an error "Exception has been thrown by the target of an invocation"
I use the metadata format:
info.txt
```
TITLE: Mezase! Rakuen Keikaku Vol. 7
AUTHOR/CIRCLE: Tora Machine
ARTIST: Kasukabe Taro
TAGS: Bikini ♀, Incest, Loli ♀, Sister ♀, Sole Female ♀, Sole Male ♂, Swimsuit ♀
DESCRIPTION: 
```

Is it possible to fix this error?

Thax!

**Comment by dodying** [comment]
which software help you download/generate the info.txt?

and share the demo file with me

**Comment by dodying** [comment]
if you know the language Python, you can try to do like the following (**Not Test**):

1. comment all line in function `parseInfoContent` after `info['Title'] = a[0]`
2. add these at the bottom of the function `parseInfoContent` **notice the indentation**
```python
  info['Writer'] = b['AUTHOR/CIRCLE'] or b['AUTHOR'] or b['CIRCLE'] or b['ARTIST']
  info['Tags'] = b['TAGS']
```

**Comment by chubits** [comment]
I use the program "https://doujindownloader.com/" 

file:
https://app.box.com/s/xduhkof2ws6vu588hye8t78ysfqa0ih1

I don't know Python very well (

**Comment by dodying** [comment]
please try latest version.

recommend to use `Tampermonkey` with `E-Hentai Downloader`
with this you can use [comicSort](https://github.com/dodying/Nodejs/tree/master/comicSort) or [comicBrowser](https://github.com/dodying/Nodejs/tree/master/comicBrowser) to organize, find or view the comic.
**NOTE:** `E-Hentai Downloader` only download the comic from exhentai.org or e-hentai.org

**Comment by chubits** [comment]
Hi, I noticed a bug with the name of the series. 
If the symbol ":" is in the name of the series, then the name of the series is trimmed after ":"

The name of the series should be: "Re: Zero kara Hajimeru Isekai Seikatsu"
But after import, I get the name of the series: "Re"

Thank you so much for helping the cool plugin!

**Comment by dodying** [comment]
i've been updated, please try latest version.

**Comment by chubits** [comment]
It works great. Thanks!
